version: '3.8'

services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - event-net

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
    networks:
      - event-net

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
    networks:
      - event-net

  event-service:
    build: ./event-service
    ports:
      - "8082:8082"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
    networks:
      - event-net

  registration-service:
    build: ./registration-service
    ports:
      - "8083:8083"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
    networks:
      - event-net

networks:
  event-net:
    driver: bridge
