version: '3.8'

services:
  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - event-net

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - event-net
    depends_on:
      - eureka-server

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "8081:8081"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    networks:
      - event-net
    depends_on:
      - eureka-server

  event-service:
    build:
      context: .
      dockerfile: event-service/Dockerfile
    ports:
      - "8082:8082"
      - "9092:9092"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - JWT_SECRET=${JWT_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
    networks:
      - event-net
    depends_on:
      - eureka-server

  registration-service:
    build:
      context: .
      dockerfile: registration-service/Dockerfile
    ports:
      - "8083:8083"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - JWT_SECRET=${JWT_SECRET}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - RAZORPAY_WEBHOOK_SECRET=${RAZORPAY_WEBHOOK_SECRET}
    networks:
      - event-net
    depends_on:
      - eureka-server

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - event-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - event-net
    depends_on:
      - prometheus

networks:
  event-net:
    driver: bridge
